### ISSUE TITLE
Set only partial path to ipopt headers

### ISSUE THREAD

**Issue by pattacini** [robotology/robotology-vcpkg-binary-ports#3] opened 2019-08-28 18:09 UTC
I've switched my local installation based on vcpkg to the use of ipopt binary port.

However, vcpkg yields only the relative path `include\coin`, instead of the complete path to the installed headers, e.g. `c:\dev\vcpkg\installed\x64-windows\include\coin`.

As a result, icub-main fails to compile, for example.

**Comment by traversaro** [comment] 2019-08-29 09:11
I am  not sure if it is a problem of the port or it is actually a problem of the `FindIPOPT.cmake` cmake file, but I reproduced indeed the issue in https://github.com/robotology/idyntree/pull/568/checks?check_run_id=205953915 .

**Comment by traversaro** [comment] 2019-08-29 11:40
Indeed the problem is in https://github.com/robotology/ycm/blob/811edb419ab9731a8bfead99b6361cc4f0f3f595/find-modules/FindIPOPT.cmake#L133, that hardcodes the value of `IPOPT_INCLUDE_DIRS` to be `${IPOPT_DIR}/include/coin` instead of properly finding the include directory location using the [`find_path`](https://cmake.org/cmake/help/v3.15/command/find_path.html) CMake command. 

While the issue is fixed in `ycm` and `icub-main`, a possible workaround is to set the `IPOPT_DIR` CMake Cache variable to `<vcpkg_parent_directory>/vcpkg/installed/x64-windows`, or for a clean build set the env variable  `IPOPT_DIR` to `<vcpkg_parent_directory>/vcpkg/installed/x64-windows`

**Closed as completed** 2019-09-02 07:56 UTC
Labels: bug
